<!DOCTYPE html>
<html lang="en">
<head>
    <title>OurApp</title>
</head>
<body>
<h1>Hello, brother.</h1><hr>
<h4>Products from NASDAQ</h4>
<h5>Here will be listProducts</h5>
<#--<#list products as product>-->
<#--    <div>-->
<#--        <p><b>${product.getName}</b> ${product.price} | <a href="/product/${product.id}">Детальніше...</a></p>-->
<#--    </div>-->
<#--    <#else>-->
<#--    <h3>Акції відсутні</h3>-->
<#--</#list>-->
<hr>
<h3>Додати нову акцію</h3>
<#--<form action="/product/create" method="post">-->
<#--    Назва компанії: <input type="text" name="title"/><br><br>-->
<#--    Опис компанії: <input type="text" name="desc"/><br><br>-->
<#--    Ціна компанії: <input type="number" name="price"/><br><br>-->
<#--    Біржа: <input type="text" name="stock_exchange"/><br><br>-->
<#--    Користувач: <input type="text" name="author"/><br><br>-->
<#--    <input type="submit" value="Додати акцію"/>-->
<#--</form>-->
</body>
</html>